import pybedtools
import os

one = (
    "AGAGAAAGCACTCACAGAAATGTCCACAAGACCAGCCTTGCGAGGCTCTGCATGAAGTGAGATGGAAGGAGCCCACAGGAGGGGTGGGCTGAAGGGAAGATGGGGCTGTCAGCTCCTTAGGAAACCCTTGGGGCCTGACCTGGCAAACTGTAACCAGATCCCTGTTGGGCTGTCCTCCTCACATCTGGCTCAGGGTCCCCATTGCAGGGAGGCCCCCTTGGCCCTTTGCCCTGGGAAGGGGTGGGCACCGGGTCACGGTGGGGTGGGTGGGGAGGTCAGAAAGGGCATGAGGCGGGGGCACAGCGGGGTGCTTTGTGCT",
    "TCTACATCTTCCTGACAGGTCCCTCTTCTGAGGCCAGGAAAAAACAACAGCCCCCTCCCACAGCAACCCATTTGTCAGCTGAAGGCCGGCCCTGCACCTTTAACCTTCTCAAAGTCAGCAGTTCCCTGTCAAGGCCCTGTGGGGCCAAGAGACAAAGATGGATGGAGGTGGCTGTTTGTAGAGGAAAGCTCTTGGCTGCAGCCAAGGGGAGTGGTCCGGAAGGGAGGGGCTCCTGGCTTCTGGTGGGGCTGGAGGTCGCCCAGGGAGGAAAAGGAAAGACACAAGTTCCAGGGGCCCTGGAGGGCCTCCAGCTGGGCCACACCTGAGCCATCCTACAGAATGCTGGGAATTTCCTCCAGTGCGCATGACAAACAGGCCTTCCTCGACCAGACAGGCCTGTTTCTGTGCTGGCCACCCCAGCCACCTGTGTGTGGAGATGCTGAAGGTCCAGGGAGGGGCTGGAGGTGGGA",
)
ten = (
    "AGAGAAAGCACTCACAGAAATGTCCACAAGACCAGCCTTGCGAGGCTCTGCCTGAAGTGAGATGGAAGGAGCCCACAGGAGGGGTGGGCTGAAGGGAAGATCGGGCTGTCAGCTCCTTAGGAAACCCTTGGGGCGTGGCCTGGCAAACTGTAACCAGATCCCTGTTGGGCTGTCCTCCTCACATCTGGCTCAGGGTCCCCATTGCAGGGAGGCCCCCTTGGCCCTTTGTCCTGGGAAGGGGTGGGCACCGGGTCACGGTGGGGCGGGTGGGGAGGTCAGAAAGGGAATGAGGCGGGGGCACAGCGGGGTCCTTTGTGAT",
    "TCTACATCTTCCTGACAGGTCCCTTTTCTGAGGCCAGGAAAAAACAACAGCCCCCTCCCACAGCGACCCATTTGTCAGCTGAAGGCCGGCCCTGCACCTTTAGCCTTCTCAAAGTCAGCAGTTCCCTGTCAAGGCCCTGTGGGGCCAAGAGACAAAGATGGATGGAGGTGGCTGTTTGTAGAGGAAAGCTCTTGGCTGCAGCCAAGGGGAGTGGTCCGGAAGGGAGGGGCTCCTGGCTTCTGGTGGGGCTGGAGGTCGCCCAGGGAGGAAAAGGAAAGACAAAAGTTCCAGTGGCCCTGGAGGGCCTCCCGCTGGGCCACACCTCAGCCATCCTACAGAATGCTGGGAATTTCCTCCAGTTCGCATGACAAAGAGGCCTTCCTCGACCAGACAGGCCTGTTTCTGTGCTGGCCACCCCAGCCACCTGTGTGTGGAGATGCTGAAGGTCCAGGGAGGGGCTGGAGGTGGGA",
)
twenty = (
    "AGAGAAAGCACTCACAGAAATGTCCACAAGACCCGCCTAGCGAGGCTCTGCCTGAAGTGAGATGGAAGGAGCCCACAGGAGGGGTGGGCTGAAGGGAAGATCGGGCTGTCAGCTCCTTAGGAAACCCTTGGGGCGTGGCCTGGCAAACTGTAACCAGATCCCTGCTGGGCTGTCCTCCTCACATCTGGCTCAGCGTCCCCACTGCAGGGAGGCCCCCTTGGCCCTTTGTCATGCGAAGGGGTGGGAACCGGGTCACAGTGGGGCGGGTGGGGAGGTCACAAAGGGAATGAGGCGGGGGCACAGCGGGGTCCTTTGTGAT",
    "TCTACATCTTCCTGACAGGTCCCTTTTCTGAGGCCAGGAAAAAACAACAGCCCCCTCCCACAGCGACCCATTTGTCAGCTGAAGGCCGGCCCTGCACCTTTAGCCTTCTCAAAGTCAGCAGTTCCCTGTCAAGGCCCTGTGGGGCCAAGAGACAAAGATGGATGGAGGTGGCTGTTTGTAGAGGAAAGCTCTTGTCTGCAGCCAAGGGGAGTGGTCCGGAAGGGAGGGGCTCCTGGCTTCTGGTGGGGCTGGAGGTCGCCCCGGGAGGAAAAGGAATGACAATAGTTCCAGTGGCCCTGGAGGGCCTCCCGCTGGGCCACACCTCAGCCATCCTACAGAATGCTGGGAATTTCCTCCAGTTTGCATGACAAAGAGGCCTTCCTCGCCCAGACAGGCCTGTTTCTGTGCTGGCCACCCCAGCCGCCTGTGTTTAGAGATGCTAAAGGTCCAGGGAGGGGCTGGAGGTGGGA",
)
fifty = (
    "AGAGGAAGCAATCAAAGAAACGTCCGCAAGACCCGCCTAGCGGGGCTCTGGCTGAATTGTGATGCAAAGAGCCCGCAGGAGGGCTGGTCTGAAGGAAACATCGGGCTGTCAGCTCCTTAGGAAACCGGTGGGGCGTGGCCTGGCAAACTGTAACCAGATCCCTGCTGGGCTGTTTTCCTCAAATCTGGCTCAGCGGCCTCATTGCAGGGAGGCCCCCTGGGCCCTTTGTTATGCAAAGGGGTGGGAACCGGCTCCCGGTGGGGCGGCTGGGGAGGTCACAAAGGGAATGAGGCGGCGGCCCAGCGGGGTCCTTTGTGAT",
    "TCTACAGCTTCCTGAAAGGTCCCTTTTGTGAGGCCAGGAAAAAACAATAGCCCCCTCCCACAGCGACCCATTTGTCAGCTGAATGCCGGCCCTGCACCTTTAGCCTTCACAAAGGCAGCAGTTCCCTTTCAAGGCCCTGTGGGGCCGCGAGACAAAGATGGCTGGAGGTGGCTGTTTGTAGCGCAAAGCTCTTGTTTGCCGCCAGGGGGAGTGGTCCGGCAGGGAGGGGCTCTTGGCTTCCGGTGGGGCTGGAGGTCTCCCCGGGAGGAAAATGAATGACAATAGTTCCAGTCGCCCTGGAGGGCCTCCCGCTGGGCCACACCTCAGCCATCCTGCAGAATGCTGGGAATTTCCTCCAGTTTGCATGACAAAGAGGCCTGCCTCGCCCAGACAGGCCTGTTTTTGTGCTGGCGACCCCAGCCGGCGGTCTTTTGAGATGCTAAAGGCCCAGGGAGGGGCTGGAGGTGGGA",
)

# ("Shh", "chr5:28469555-28469773", "chr5:28469862-28470083")
name = "Meox1"
region1 = "chr11:101896575-101896894"
region2 = "chr11:101896977-101897447"

genome = pybedtools.BedTool("/gpfs/gibbs/project/garg/shared/catalogs/gencode_fastas/GRCm38.primary_assembly.genome.fa")


# Helper to extract sequence from BedTool
def get_seq(chrom, start, end):
    # bed = pybedtools.BedTool(f"{chrom}\t{start}\t{end}", from_string=True)
    return str(pybedtools.BedTool.seq((chrom, start, end), genome))


# Parse coordinates
chrom, s1, e1 = region1.replace("chr", "").split(":")[0], *region1.split(":")[1].split("-")
_, s2, e2 = region2.replace("chr", "").split(":")[0], *region2.split(":")[1].split("-")

# Convert to ints
s1, e1, s2, e2 = map(int, (s1, e1, s2, e2))

# Get linker region
linker_seq = get_seq("chr11", e1, s2)
front = get_seq("chr11", s1 - 1000, s1)
end = get_seq("chr11", e2, e2 + 1000)
# Make combined sequences
print(len(front), len(one[0]), len(linker_seq), len(one[1]))
combined = {
    "meox1_one.fasta": front + one[0] + linker_seq + one[1] + end,
    "meox1_ten.fasta": front + ten[0] + linker_seq + ten[1] + end,
    "meox1_twenty.fasta": front + twenty[0] + linker_seq + twenty[1] + end,
    "meox1_fifty.fasta": front + fifty[0] + linker_seq + fifty[1] + end,
}

# Write FASTA files
for fname, seq in combined.items():
    with open(fname, "w") as f:
        f.write(f">{fname.replace('.fasta','')}\n")
        f.write(seq)
    os.system(f"samtools faidx {fname}")

print("FASTA files written:", list(combined.keys()))
